language: node_js
dist: trusty
sudo: required
node_js:
- "10.15.3"
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
- npm install
script:
- npm run lint    || travis_terminate 1;
- npm run build   || travis_terminate 1;
- npm run test    || travis_terminate 1;
- npm run publish || travis_terminate 1;
- npm run deploy  || travis_terminate 1;
notifications:
  email:
    recipients:
    - guyso@wix.com
cache:
  directories:
    - node_modules