language: node_js
dist: trusty
node_js:
- "8.11.3"
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm run lint    || travis_terminate 1;
- npm run build   || travis_terminate 1;
- npm run test    || travis_terminate 1;
- npm run publish || travis_terminate 1;
- npm run deploy  || travis_terminate 1;
notifications:
  email:
    recipients:
    - guyso@wix.com
cache:
  directories:
    - node_modules